name: Automate dumptruck release
# Workflow trigger Event
on:
  release:
    types: [published]
    
jobs:
  build:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
# This action will log in against a Docker registry. 
        - name: Login to DockerHub Registry
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
# This action will Build and Push the latest Docker image to Docker Hub.
        - name: Build and push
          uses: docker/build-push-action@v3
          with:
            push: true
            tags: meshcloud/dumptruck:latest
