name: Automate dumptruck release

on:
  release:
    types: [published]

jobs:
  build:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - name: Login to DockerHub Registry
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
        - name: Build Docker image
          run: docker build . --file Dockerfile --tag meshcloud/dumptruck:latest
        - name: Push the Docker image
          run: docker push meshcloud/dumptruck:latest
        - name: Build the latest Docker image
          run: docker build . --file Dockerfile --tag meshcloud/dumptruck:latest
        - name: Push the latest Docker image
          run: docker pull meshcloud/dumptruck:latest